
# Secret for MariaDB sensitive data (root and user passwords)
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  mysql_root_password: {{ .Values.secret.mysql_root_password }}
  mysql_password: {{ .Values.secret.mysql_password }}   