
# Service to expose MariaDB internally
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: mariadb
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}