
# Secret for WordPress sensitive data (MySQL password)
apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  db_password: {{ .Values.secret.db_password }}
